name: 🐛 Bug Report
description: Report something broken
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is broken?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce it?
      placeholder: |
        1.
        2.
        3.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior

  - type: textarea
    id: env
    attributes:
      label: Environment